=== 919126624/Feiying-/cmct/src/main/resources/query/query.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" 
	targetNamespace="http://www.dingjiansoft.com/query" 
	xmlns="http://www.dingjiansoft.com/query" 
	elementFormDefault="qualified">
	<xsd:element name="querys">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="query" minOccurs="0" maxOccurs="9999">
					<xsd:complexType>
						<xsd:sequence>
							<xsd:element name="columns" minOccurs="1" maxOccurs="1">
								<xsd:complexType>
									<xsd:sequence>
										<xsd:element name="column" minOccurs="1" maxOccurs="9999">
											<xsd:complexType>
												<xsd:attribute name="field" type="xsd:string" use="required"/>
												<xsd:attribute name="display" type="xsd:string" use="required"/>
												<xsd:attribute name="width" type="xsd:integer" use="required"/>
												<xsd:attribute name="align">
													<xsd:simpleType>
														<xsd:restriction base="xsd:string">
															<xsd:enumeration value="left" />
															<xsd:enumeration value="center" />
															<xsd:enumeration value="right" />
														</xsd:restriction>
													</xsd:simpleType>
												</xsd:attribute>
												<xsd:attribute name="hidden" default="false" />
											</xsd:complexType>
										</xsd:element>
									</xsd:sequence>
								</xsd:complexType>
							</xsd:element>
						</xsd:sequence>
						<xsd:attribute name="id" use="required"/>
						<xsd:attribute name="mapper" use="required"/>
						<xsd:attribute name="keyDefault" use="optional"/>
					</xsd:complexType>
				</xsd:element>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
</xsd:schema>

=== 919126624/Feiying-/hr/target/classes/query/hrQuery.xml
<?xml version="1.0" encoding="UTF-8"?>
<querys xmlns="http://www.51zhiye.com/query"
		xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		xsi:schemaLocation="http://www.51zhiye.com/query query.xsd">
	<!-- 款项类别 的f7-->
    <query mapper="com.wuyizhiye.hr.attendance.dao.LeaveDao.select" id="queryLeave">
		<columns>
			<column width="80" field="billNumber" display="单据编号" align="left"/>
			<column width="80" field="applyPerson.name" display="申请人" align="left"/>
			<column width="80" field="personPosition.name" display="岗位" align="left"/>
			<column width="80" field="applyPerson.org.name" display="部门" align="left"/>
			<column width="80" field="ask4LeaveType.label" display="请假类型" align="left"/>
			<column width="80" field="ask4LeaveStatus.label" display="请假状态" align="left"/>
			<column width="120" field="description" display="描述" align="left"/>
		</columns>
	</query>
	  <query mapper="com.wuyizhiye.hr.salary.dao.SalaryItemDao.select" id="querySalaryItem">
		<columns>
			<column width="80" field="number" display="编号" align="left"/>
			<column width="80" field="name" display="名称" align="left"/>
			<column width="120" field="remark" display="描述" align="left"/>
		</columns>
	</query>
</querys>
